num_iterations: 20
ratio: 0.2
k1: 30
k2: 20
file_types: pcd  # options: pcd / npz
data_path:  "/home/yunqi/Desktop/lt_slam/loop_pairs/npz/"
data_path0: "/home/yunqi/Desktop/lt_slam/loop_pairs/scans/000166.pcd"
data_path1: "/home/yunqi/Desktop/lt_slam/loop_pairs/scans/000468.pcd"
descriptor: "fpfh"
inlier_threshold: 0.6
d_thre: 0.1
downsample: 0.3
re_thre: 5
te_thre: 60
num_node: 8000  # 0 means all of nodes
use_mutual: false
max_points: 20000
nms_radius: 0.6
